image: node:10

cache:
  paths:
    - node_modules

stages:
  - build
  - test

before_script:
  - yarn

build:
  stage: build
  script: yarn build
  tags:
    - docker

test:
  stage: test
  script: yarn test
  tags:
    - docker

lint:
  stage: test
  script: yarn lint
  tags:
    - docker
